### ISSUE TITLE
Add better exception message for when accessing the keychain fails on SSH

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-extensions-for-dotnet#112]
The login Keychain is not unlocked when connecting via an SSH session. You can manually do this by running:

security unlock-keychain -p $PASSWORD $KEYCHAIN

..where PASSWORD is the user’s password, and KEYCHAIN is the path to the user’s login Keychain (i.e, /Users/<username>/Library/Keychains/login.keychain-db).

It’s not very elegant but does seem to work in my limited testing.
Probably something you could detect (a locked keychain from a remote session), catch the error, and tell the user to manually unlock the login Keychain with that command?

**Comment by rayluo** [comment]
Good idea. Upvoted.

Quick question. Why would such exception only happen "when WRITING to keychain on ssh"? Wouldn't reading trigger same exception?

**Comment by bgavrilMS** [comment]
@rayluo - you are right, the read would fail first.
