### ISSUE TITLE
Prevent PlatformNotSupportedException to be thrown

### ISSUE THREAD

**Issue by tipa** [AzureAD/microsoft-authentication-extensions-for-dotnet#115]
In order to have my macOS app to break at the location where an exception is thrown, I enabled a global Exception catchpoint:
![Screenshot 2020-11-25 at 18 05 14](https://user-images.githubusercontent.com/2863198/100259700-ca1d4a00-2f48-11eb-9412-fb9e57fab453.png)

Now this causes my app to break every time I call `MsalCacheHelper.CreateAsync`because a PlatformNotSupportedException is being thrown internally (see https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/issues/61).

Is there perhaps a way to prevent the exception to be thrown so my app is not switching into debugging mode?

**Comment by bgavrilMS** [comment]
Hi @tipa - I think the root cause may be https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2251 ? Which we will fix with MSAL 4.24

**Comment by tipa** [comment]
No, this is a different issue. It has been present since I started using the library.
The exception is being caught (see below), but I am still being thrown into Debugging mode every time and I haven't found a way in Visual Studio for Mac to prevent that 

https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/2ba33180761b8782757421741239b8b0967bdff1/src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs#L232-L237

Based on this setting in Visual Studio it should not stop however.
![Screenshot 2020-11-30 at 15 46 38](https://user-images.githubusercontent.com/2863198/100624228-7c775780-3323-11eb-9d4f-40874fc0ccc5.png)

If you think this is a VS issue, let me know and I will post this into the Visual Studio feedback forums
