### ISSUE TITLE
Cache helper in a .NET (Framework) service

### ISSUE THREAD

**Issue by RegisStGelais** [AzureAD/microsoft-authentication-extensions-for-dotnet#116]
I want to use the cache helper to share the cache between my system tray UI app (.NET Framework Desktop app) and my background service (.NET Framework service)

My UI app can read and write my cache file but my system is not able to access it.

Any Hints ?

**Comment by jmprieur** [comment]
@RegisStGelais : do your applications have the same client ID?
Applications can only share tokens if they have the same client ID (3P)

**Comment by RegisStGelais** [comment]
Yes.
In fact all the MSAL code is inside a dll.
Both the UI APP and the service call the same dll.

Also, I specify a path where to put the cache file that is not based on the windows user.

**Comment by jmprieur** [comment]
What does it mean, @RegisStGelais for your system not being able to access it? do you have repro steps? errors? exceptions?

**Comment by RegisStGelais** [comment]
It does not give me an exception, It just do not return the cached account. and then of coarse, AcquireTokenSilent fails with the expected exception when no account info is passed to it
MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.
I will investigate further but it's a bit harder to debug a dll when it is called by a service.
The same dll works perfectly when called from the UI app.

**Comment by RegisStGelais** [comment]
I found how to attach the debugger to my running service.
What I found so far is that  accounts.FirstOrDefault() returns null.
I will keep digging.

**Comment by RegisStGelais** [comment]
Here are the exceptions that I get while debugging the service at the moment it tries to get the token:

Exception thrown: 'System.Security.Cryptography.CryptographicException' in System.Security.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in mscorlib.dll
'UmtSyncService.exe' (CLR v4.0.30319: UmtSyncService.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. Symbols loaded.
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in mscorlib.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in mscorlib.dll
MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call.

**Comment by RegisStGelais** [comment]
Looks like the cryptography does not like the fact that the service is not logged to the same user as the UI app.
Is there a way to tell the cachehelper to not use the cryptography and to store as plain text like it is possible to do if running on a linux platform ?

**Comment by RegisStGelais** [comment]
I ended up cresting my own simple token cache helper based on the serialization sample code on this page: [https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization](url)

**Comment by jmprieur** [comment]
@RegisStGelais 
did you try to move your .NET framework app to .NET framework 4.7.2?

**Comment by RegisStGelais** [comment]
also tried with 4.8

The issue is clear. The library uses the Microsoft cryptographie  and the lib encode and decode bases on the windows user.
Since my service and my UI app are not using the same windows user then it can't work.

I simply configure the tokenCache.SetBeforeAccess and tokenCache.SetAfterAccess events to my own cache file read and write and I encrypt/decrypt using a cryptography routine that is not based on the authentifier windows user.

**Comment by jmprieur** [comment]
Thanks for the full explanation, @RegisStGelais
