### ISSUE TITLE
MsalCacheHelper.Clear() method - change behavior instead of deprecation

### ISSUE THREAD

**Issue by rabenshm** [AzureAD/microsoft-authentication-extensions-for-dotnet#121]
Following offline talk with Bogdan, we agreed that it is better instead of deprecating the MsalCacheHelper.Clear() method, to change its behavior that it will only clear the cache entries relevant to the specific public client application id that the MsalCacheHelper object was created with, and not whole entries in the cache file itself.

**Comment by bgavrilMS** [comment]
Problem is that MsalCacheHelper is constructed with a `client_id` however Clear() method simply removes the data file, i.e. clears the cache for all client_id.

**Comment by bgavrilMS** [comment]
I will have removed the need to pass in the client_id to the cache with the associated PR. So with next release - 2.18.0 - you can have a single instance of `MsalCacheHelper`. 

To sign out users, you need to use MSAL i.e. call `RemoveAccountAsync`. Wiping out the token cache file is discouraged, we will only keep the method for backwards compatibility reasons.

Ping me to discuss further.
