### ISSUE TITLE
Upgraded to latest pkg broken saving cache

### ISSUE THREAD

**Issue by ivberg** [AzureAD/microsoft-authentication-extensions-for-dotnet#122]
We were on .NETCore 3.0 and these versions:
 PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="2.15.0"
 PackageReference Include="Microsoft.Identity.Client" Version="4.25.0"

Now upgraded to .NETCore 3.1 with the latest:
 PackageReference Include="Microsoft.Identity.Client" Version="4.25.0"
 PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="2.16.8"

I was not able to see precisely which version broke things because of NuGet pkg downgrade dependency hell.

Msal continues to work prompting for authentication via the browser (and succeeds) but saving to the cache no longer works. A new cache file is created but upon subsequent relaunch of the app the cache no longer succeeds and the user is prompted again.

<Code Snippet>
            var user = "unknown";
            string domainaccount = WindowsIdentity.GetCurrent().Name;
            if (!String.IsNullOrWhiteSpace(domainaccount))
            {
                var domainaccountSplit = domainaccount.Split('\\');
                if (domainaccountSplit.Length >= 2)
                {
                    user = domainaccountSplit[1];
                }
            }      

			var myApp_AppData = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Microsoft\\MyApp");
            var storageCreationPropertiesBuilder = new StorageCreationPropertiesBuilder(
                $"MyApp.{user}.msalcache.bin3",
                myApp_AppData,
                MyAppClientAppGuid.ToString()
                );
            var storageCreationProperties = storageCreationPropertiesBuilder.Build();
            var msalCacheHelper = MsalCacheHelper.CreateAsync(storageCreationProperties).GetAwaiter().GetResult();
            msalCacheHelper.RegisterCache(app.UserTokenCache);

            AuthenticationResult result;
            var account = app.GetAccountsAsync().GetAwaiter().GetResult().FirstOrDefault();

            try
            {
                result = app
                    .AcquireTokenSilent(scopes, account)
                    .ExecuteAsync()
                    .GetAwaiter()
                    .GetResult();

            }
            catch (MsalUiRequiredException)
            {
                result = app
                    .AcquireTokenInteractive(scopes)
                    .ExecuteAsync()
                    .GetAwaiter()
                    .GetResult();
            }

            return result;
</Code Snippet>

**Comment by jmprieur** [comment]
Can you please tell us which version of the library you used to use with .NET Core 3.0, and which do you use with .NET Core 3.1. Do you have a full repro project?

**Comment by ivberg** [comment]
Apologies - the versions were included in the original issue submission, but were invisible since it looks like GitHub markup was hiding the version since there were in XML tags. I removed the surrounding tags so you can see the before/after versions

**Comment by bgavrilMS** [comment]
Looking at this now.

**Comment by bgavrilMS** [comment]
Was not able to reproduce this. I tried the exact versions you mentioned. `AcquireTokenSilent` always works for me. 

Is this happening for some users only? Do you have a reliable repro? Feel free to ping me and we can try to debug.

**Comment by ivberg** [comment]
Debugged with @bgavrilMS - thx!

So it looks there were multiple issues here:
1. There was a build file copy issue related to new pkgs with different build dates on dlls that now had different build order/date than before. Our project uses DPAPI System.Security.Cryptography.ProtectedData.dll which this lib uses to save/protect creds on Windows. It seems normally that this "stub" (21KB) dll copied to $(OutDir) (on Windows) has a NotImplementedException for DPAPI but somehow magically redirects to the full dll (33kB) under runtimes\win\lib\netstandard2.0. That is in the standard case so it just works.
But our exe uses AssemblyLoadContext to load potentially different versions of the same named dll, and apparently our implementation made it so this magic doesn't work and the stub with NotImplementedException would be thrown and used instead. We had a workaround which is to copy the real dll in it's place. This workaround broke with the pkg upgrade because now the stub version was newer than the real .dll (xcopy /D) so although the dll copy code was the same, the runtime still broke.

This coupled with (2) below made this silently break w/o any exceptions/warnings. Build Fix To Always copy the .dll even if the one it's replacing is newer
// -- added so GitHub shows XML code
FROM:
--  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
--    <Exec Command="CALL XCOPY /**d**ickherfy $(ProjectDir)$(OutDir)runtimes\win\lib\netstandard2.0\System.Security.Cryptography.ProtectedData.dll $(ProjectDir)$(OutDir)" />
--    <Exec Command="CALL XCOPY /**d**ickherfy $(ProjectDir)$(OutDir)runtimes\win\lib\netcoreapp2.1\System.Security.Principal.Windows.dll $(ProjectDir)$(OutDir)" />
--  </Target>

TO:
--  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
--    <Exec Command="CALL XCOPY /ickherfy $(ProjectDir)$(OutDir)runtimes\win\lib\netstandard2.0\System.Security.Cryptography.ProtectedData.dll $(ProjectDir)$(OutDir)" />
--    <Exec Command="CALL XCOPY /ickherfy $(ProjectDir)$(OutDir)runtimes\win\lib\netcoreapp2.1\System.Security.Principal.Windows.dll $(ProjectDir)$(OutDir)" />
--  </Target>

2. As mentioned above MsalCacheHelper doesn't throw exceptions when trying to use or create saved tokens, thus this silently broken /w no good exceptions stating why. It was suggested we use this API call which does help say what the exact issue is and is helpful -             msalCacheHelper.VerifyPersistence(); // If there is an issue with DPAPI System.Security.Cryptography.ProtectedData.dll this will catch it where-as lib use above will silently fail and swallow exceptions

**Comment by bgavrilMS** [comment]
@jmprieur @henrik-me - the main problem here is that the cache ext does not throw exceptions, because MSAL can just work with in-memory cache. This is making investigations into issues much more complex, as developers just see that `AcquireTokenSilent` always fails, but have no idea why.

I think we should take a small breaking change here and make this token cache impl throw exceptions instead of swallowing them. We can have existing customer configure a flag to opt-out of exceptions instead.

**Comment by henrik-me** [comment]
@bgavrilMS not sure we can can make such a breaking change, we can do opt in, and do that in our sample code. Perhaps another job for the analyzer/best practice tool. We can also highlight the importance of using ValidatePersistence() ?

**Comment by jmprieur** [comment]
Which exception do we throw, @bgavrilMS? the one related to the IOs?

**Comment by bgavrilMS** [comment]
In this particular case, @jmprieur , the problem is on Windows with DPAPI, as the DPAPI.dll used by the program was throwing a NotImplementedException.

**Comment by bgavrilMS** [comment]
For logging, VS automatically adds a trace listener to its output window 

![image](https://user-images.githubusercontent.com/12273384/107511086-ea01f880-6b9c-11eb-8945-edeb3470328e.png)

**Comment by bgavrilMS** [comment]
I spent some time figuring out logging in this library and documented it [here](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/wiki/Logging)
