### ISSUE TITLE
MsalCacheHelper.CreateAsync throws HttpRequestException when offline

### ISSUE THREAD

**Issue by FreddyD-GH** [AzureAD/microsoft-authentication-extensions-for-dotnet#123]
**Desired behavior**
I would like to be able to read the accounts from the cache, even when the user does not have an internet connection.  It is my understanding that this functionality works when using MSAL with token caches on other platforms.  Is there any reason offline functionality should not be possible with the token cache provided in this repo?

**Actual behavior**
When I call `MsalCacheHelper.CreateAsync`, it throws a `HttpRequestException` with the message `No such host is known`.

**Miscellaneous**
- The app I am using is a .NET 5.0 WPF app.
- I am using version 2.16.7 of Microsoft.Identity.Client.Extensions.Msal

**Comment by bgavrilMS** [comment]
What is your authority? 

This is a valid bug, generally MSAL is able to perform GetAccount offline. As long as you connect to some known clouds, this should work offline. MSAL needs to go online if the are tokens in the cache for authorities it does not recognize.

**Comment by FreddyD-GH** [comment]
I am using `.WithB2CAuthority()` with the form `xxx.b2clogin.com`.
