### ISSUE TITLE
Unresolved P/Invoke method build warning for UWP using msal

### ISSUE THREAD

**Issue by kevcrooks** [AzureAD/microsoft-authentication-extensions-for-dotnet#129]
We've received the following build warning for our UWP app which uses `Microsoft.Identity.Client 4.22.0` and `Microsoft.Identity.Client.Extensions.Msal 2.16.5`. 

The app and authentication appears to be working ok, but I wondered if this is a problem, or there is something we need to do to fix the warning?

`
##[warning]C:\Users\VssAdministrator\.nuget\packages\microsoft.net.native.compiler\2.2.9-rel-29512-01\tools\Microsoft.NetNative.targets(805,5): Warning :       MCG : warning MCG0007: Unresolved P/Invoke method 'libsecret-1.so.0!secret_schema_new' for method 'System.IntPtr Microsoft.Identity.Client.Extensions.Msal.Libsecret.secret_schema_new(System.String, System.Int32, System.String, System.Int32, System.String, System.Int32, System.IntPtr)'. Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
`

We receive about 10 similar warnings for different P/Invoke methods related to the package - is the possible runtime exception something we can fix?

**Comment by bgavrilMS** [comment]
This library calls into KeyChain and KeyRing on Mac / Linux. Those methods will not be called on Windows.

That said, this library wasn't designed for use with UWP, because on UWP, MSAL will store the token cache in a DPAPI protected file on its own. You do not need to customize the cache.
