### ISSUE TITLE
Memory leak of ITokenCache objects

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-extensions-for-dotnet#132]
1. Create singleton `MsalCacheHelper`
2. Create a bunch of `PublicClientApplication` objects (common scenario - one per authority, one per client id, etc.)
3. For each `PublicClientApplication` call `helper.RegisterCache(pca.UserTokenCache)`
4. Let `PublicClientApplication` be garbage collected

**Actual**: the UserTokenCache objects do not get cleanded up leading to a small memory leak.

Note: this is a customer reported problem

**Comment by bgavrilMS** [comment]
The singleton `MsalCacheHelper`

There are 2 solutions to this: 

1. Call the equivalent `helper.UnregisterCache` which will ensure the helper does not hold onto the `ITokenCache` object

2. Msal Cache Extension does not really have any business holding on to the ITokenCache objects. It was done some time ago in an attempt to optimize access, most code was deleted but some of it remains. We can remove all the old code, Visual Studio should not be affected by this.

**Comment by jmprieur** [comment]
@bgavrilMS:  Could we have the helper.RegisterCache method return an `IDisposable`

**Comment by bgavrilMS** [comment]
@jmprieur - we could, but it makes for a more complicated API. My proposal (see attached PR) is to stop keeping ITokenCache objects pointlessly. I have validated this approach with VS and they are ok with it.
