### ISSUE TITLE
[Feature Request] Use credential manager instead of local file store for token caching on Windows platforms

### ISSUE THREAD

**Issue by brphelps** [AzureAD/microsoft-authentication-extensions-for-dotnet#136]
**Is your feature request related to a problem? Please describe.**
I'm used to most other credential manager type functions to use Credential Manager in windows (e.g. git and nuget credential managers both do this on windows IIRC). It seems inherently more secure -- I'm assuming cred manager access is audited, and that permissions are more tightly controlled than they might be in a file system. This feature request might just as well be the question: Why is MSAL using local file storage instead of the credential manager store?

**Describe the solution you'd like**
Having windows execution use Credential Manager to store tokens. 

**Describe alternatives you've considered**
I think the existing implementation is an alternative, but it seems less secure than using credential manager.

**Comment by bgavrilMS** [comment]
@brphelps  - MSAL on its own will not store tokens anywhere for .NET Fx and .NET Core runtimes. You have to customize storage. We offer a solution for this here: https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/ which seems to satisfy your needs, including Linux fallback.
