### ISSUE TITLE
[Bug] Null Reference Exception Thrown in RegisterCache on Mac

### ISSUE THREAD

**Issue by jfullerton44** [AzureAD/microsoft-authentication-extensions-for-dotnet#147]
![image](https://user-images.githubusercontent.com/12804248/126712449-38cde2f9-dd88-422b-b3f1-1fa1d013d3d5.png)
When RegisterCache is run on mac a null reference is thrown in Msal.MacKeyChain.DeleteKey(String serviceName, String accountName). This issue does not appear on linux or windows at the moment.

Issue appears on Mac OS 11.4 (20F71)
Msal version 2.18.7

**Comment by trwalke** [comment]
Adding P1 as this is throwing a null ref

**Comment by bgavrilMS** [comment]
@jfullerton44 - looking at the stack trace above, I don't think you are using a recent version of the library. 

[Microsoft.Identity.Client.MSAL.Extensions](https://www.nuget.org/packages/Microsoft.Identity.Client.Extensions.Msal/) is currently at version 2.18.8 and MSAL itself is at 4.35.

MsalCacheStorage.ClearCore was removed by [this commit](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/commit/560e117552f5e083f88b13d3a9ac84d1e55642be#diff-ca65265e5aaf33c5209c367d4e1958114fd2080e1ea77235414909f5c5c59407L296), exactly 2 years ago. 

Can you please upgrade to latest versions of MSAL and cache ext and try again?

**Comment by jfullerton44** [comment]
I updated MSAL to 4.35 and Extensions to 2.18.8 and this is the stack trace now 
![image](https://user-images.githubusercontent.com/12804248/127032055-d8735541-b98e-4f2b-b499-7fb07ad5c55b.png)

**Comment by jfullerton44** [comment]
I seem to have found the issue. When the StorageCreationPropertiesBuilder was being created I needed to add the service and account name using 
```.
WithMacKeyChain(
    "msal_service",
     "msal_account");
```

After I added this the issue went away.  This also explains why the issue was only appearing on mac

**Comment by bgavrilMS** [comment]
Yes, but please  add something more descriptive than "msal_service" / "msal_account". Use the name of your app.
