### ISSUE TITLE
CrossPlatLock does not work on UWP

### ISSUE THREAD

**Issue by fuocor** [AzureAD/microsoft-authentication-extensions-for-dotnet#151]
the following line in `CrossPlatLock.cs` does not work on UWP and results in a `SystemException: Retrieving information about local processes is not supported on this platform.`

`writer.WriteLine($"{Process.GetCurrentProcess().Id} {Process.GetCurrentProcess().ProcessName}");`

**Comment by bgavrilMS** [comment]
This project is not compatible with UWP indeed. 

There is no need to configure token caching on UWP, MSAL does it for you. It stores the cache in a File encrypted with DPAPI. Implementation is [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/c7c5da309d0b5d9973bdadf0a047357fd5cfa1a9/src/client/Microsoft.Identity.Client/Platforms/uap/SynchronizedAndEncryptedFileProvider.cs).

You can change that implementation if you wish - see https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=custom
