### ISSUE TITLE
How to prompt for account selection and then check the cache for a token instead of always requiring a password?

### ISSUE THREAD

**Issue by Metritutus** [AzureAD/microsoft-authentication-extensions-for-dotnet#158]
When logging in with MSAL for .NET, the recommended approach is to attempt `IClientApplicationBase.AcquireTokenSilent()` first, using an account from `IClientApplicationBase.GetAccountsAsync()`, and if that fails, then prompt the user with something like `IPublicClientApplication.AcquireTokenInteractive()`.

I am using the cache functionality from this repo to cache to a file and register it using `RegisterCache()`.

What I am looking to do is to _not_ use `AcquireTokenSilent()`, but instead to always show the list of accounts that are remembered using `AcquireTokenInteractive()`, and have the user select one.  If a token is then found in the cache for this account, then it logs them in.  If it does not, then it prompts for the password, then 2FA, etc.

Right now, this behaviour is only demonstrated if having already signed in while the app is running, which suggests that there's something being stored in memory which is not persisted into the cache file.

I should emphasise that `AcquireTokenSilent()` does seem to work, suggesting that the cache is working as intended.

Rough code being used:

```csharp
var scopes = new string[] { "api://" + clientId + "/user.read" };

StorageCreationProperties storageCreationProperties = new StorageCreationPropertiesBuilder(cacheFileName, cacheDirectory).Build();
MsalCacheHelper cacheHelper = await MsalCacheHelper.CreateAsync(storageCreationProperties).ConfigureAwait(false);

IPublicClientApplication app = PublicClientApplicationBuilder.Create(clientId)
    .WithAuthority("https://login.microsoftonline.com/common/", true)
    .WithRedirectUri("https://login.microsoftonline.com/common/oauth2/nativeclient")
    .Build();
    
cacheHelper.RegisterCache(app.UserTokenCache);

IAccount existingAccount = (await app.GetAccountsAsync().ConfigureAwait(false)).FirstOrDefault();

if (existingAccount != null)
{
    try
    {
        authenticationResult = await app.AcquireTokenSilent(scopes, existingAccount).ExecuteAsync().ConfigureAwait(false);
    }
    catch (MsalUiRequiredException)
    { }
}

// If this line is commented-out, the user is STILL prompted for a password
// unless this method has already run once and that user has entered their password
// and successfully logged in during this run of the app.
if (authenticationResult == null)
{
    try
    {
        authenticationResult = await app.AcquireTokenInteractive(scopes)
                                            .WithCustomWebUi(...)
                                            .ExecuteAsync()
                                            .ConfigureAwait(false);
    }
    catch (MsalClientException ex)
    { }
}
```

Right now the only alternative I can see is have the app display its own list of the available accounts in its own UI and then attempt `AcquireTokenSilent()` on the selected one.  This obviously means that, from a user-experience perspective, it would stand apart from the standard Microsoft authentication UI.

Is there a built-in way to accomplish the functionality that I've mentioned above?  Or is the approach I mentioned in the last paragraph my only option?  Is there any documentation available on this?

**Comment by Metritutus** [comment]
> Hi @Metritutus ,
> 
> MSAL offers a fairly low level API, and does not do account management for you. Typically account management is done in 2 ways:
> 
> 1. Single account applications
> 
> a. Most apps only deal with 1 account being logged in at one time. The first time the app starts, `AcquireTokenSilent` will fail and `AcquireTokenInteractive` takes over. b. The 2nd time the app starts, `AcquireTokenSilent` works. c. If the user wishes to change that account, they "sign out". You clear the cache and a. begins again d. If 2FA is needed, AcquireTokenSilent also fails (same exception, but different reason) and you call AcquireTokenInteractive again.
> 
> I suggest you add `WithAccount(acc)` to AcquireTokenInteractive for this case, to provide an optimized experience in the browser. Alternatively, provide `WithLoginHint`
> 
> You can also choose to play around with `WithPrompt`, which controls how the browser behaves.
> 
> Note that: WithAccoutn, WithLoginHint and WithPrompt are the only ways to control the behavior of the browser.
> 
> 2. Multi-Account apps
> 
> Visual Studio is a multi-account app. It maintains several accounts signed in. It can , for example, display the Azure VMs you are using across all accounts / subscriptions etc. In this mode, you must write more code to define sing out experience but also to define things like "who's the current user".
> 
> I assume your app is "single account", so please see above. Note that If you skip on `AcquireTokenSilent` then:
> 
> * users are prompted for tokens more often than they need to
> * if you ask AAD for tokens too often, they will throttle you

With regards to the app type, different users may potentially sign into it on a single machine (although only one-at-a-time), so it could probably be considered a multi-account app.  However, if this approach is not recommended, do let me know.

With regards to my request and 'account management' functionality, the functionality I was looking for seemed to be functionality that was already there.

If the application is already running, and one user (or more, I assume, although I confess I haven't two accounts to test on the dev-side yet) has already 'signed-in' during that run of the application, they are not prompted again for credentials by `AcquireTokenInteractive()`.  It displays the list of accounts and clicking on the username will immediately sign the user in.  No further 2FA prompts are requested.

It is only between runs of the application that it will prompt for credentials if `AcquireTokenInteractive()` is used, and `AcquireTokenSilent()` must be used instead to avoid unnecessarily prompting the user.

If your recommendation is that `GetAccounts()` be used and the application display the list of accounts itself, then that is what I shall have to do, however I wanted to be sure I was not missing anything, as it looked like the desired functionality was already there and that there was something I specifically needed to do to enable it as desired.  Building a custom account list UI in the app itself does detract a little from the Microsoft sign-in look-and-feel experience.

**Comment by bgavrilMS** [comment]
Sorry for replying so late. 

If different users access you app one at a time, and you log out (i.e. call `app.RemoveAsync(accont)`) one user before logging in the next, then it's still a single user app. As such `GetAccounts` should only return 1 and only 1 account (or 0 the first time), hence this pattern works: 


```csharp
var app = // create app and add token caching
try 
   var theAccountOrNull = app.GetAccounts().SingleOrDefault();
   authResult = app.AcquireTokenSilent(theAccountOrNull); // 

catch MsalUiRequiredException  // can get here is no account is in the cache or if MFA is required by AAD

   authResult = app.AcquireTokenInteractive()
                              .WithAccount(theAccountOrNull) // in case of MFA< don't show the user the whole list of accounts; instead fill in the username for him/her

```

**Comment by bgavrilMS** [comment]
See our samples for details: https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#desktop
