### ISSUE TITLE
1st party app using RPS

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-extensions-for-dotnet#162]
Hi ,  Does this extension allow for .NET 4.7.2 to get rid of RPS and still get PUID in the claim?  For 1st party app.  We want to remove RPS from our app but currently cannot upgrade to .NET Core due to many .NET Framework dependencies.

I am just needing this to sign in users,  and get PUID claim  but without RPS.

**Comment by bgavrilMS** [comment]
MSAL repository https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
