### ISSUE TITLE
How to handle the locked default collection of Linux keyring when using msal storage?

### ISSUE THREAD

**Issue by msJinLei** [AzureAD/microsoft-authentication-extensions-for-dotnet#163]
Hi team,

I am using the storage API in MSAL to store service principal credentials as we previously requested https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/issues/92

In Linux, the default collection of Keyring is reported locked when I create a storage and a password input is required.
It is not the behavior we want. How can we suppress the password input? Does msal token cache handle the similar issue?

BTW, I create storage using the following codes.
```
        var storageProperties = new StorageCreationPropertiesBuilder(fileName, directory)
                                    .WithMacKeyChain(KeyChainServiceName + ".other_secrets", fileName)
                                    .WithLinuxKeyring(LinuxKeyRingSchema, LinuxKeyRingCollection, fileName, LinuxKeyRingAttr1, LinuxKeyRingAttr2);

        Storage _storage = Storage.Create(storageProperties.Build());
```

**Comment by bgavrilMS** [comment]
No reply, closing.
