### ISSUE TITLE
LocalMachine-scoped cache serialization

### ISSUE THREAD

**Issue by troplin** [AzureAD/microsoft-authentication-extensions-for-dotnet#164]
Currently, the scope is hard-coded to the `CurrentUser`, e.g. for DPAPI protection and probably also for the Mac KeyChain and Linux Keyring (although I'm not using those).
For certain applications it would be great if the scope could be changed to use the `LocalMachine` scope.

**Comment by bgavrilMS** [comment]
What would be the scenario for this @troplin? The token cache is for one user only. Generally, there is a 1:1 mapping between OS account and application account, i.e. if I login with my work account to the operating system I also login with it to my IDE (e.g. Visual Studio Code). 

The problem with sharing credentials between users is that User2 can steal User1's refresh token, which would give it complete access to many resources on behalf of User1.

**Comment by bgavrilMS** [comment]
Rejecting as it could be misused.
