### ISSUE TITLE
Race condition in setting 600 permissions

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [AzureAD/microsoft-authentication-extensions-for-dotnet#174]
[FileWithPermissions.WriteToNewFileWithOwnerRWPermissionsUnix](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/93354933e6676c86a7d9cb479fdfe8f21aecf82c/src/Microsoft.Identity.Client.Extensions.Msal/Accessors/FileWithPermissions.cs#L62-L93) first calls `File.Create` to create the file with default permissions, and then calls `chmod` to change the permissions to 600 (octal) so that the owner has read and write access, and the group and other users have no access. This `chmod` is intended to prevent malicious users from reading secrets from the file, even if the `umask` of the process allows read access to be granted to such users.

However, if a malicious user is able to open the file between the `File.Create` and `chmod` calls, then the malicious user can keep the file descriptor open, wait for the library to write secrets to the file, and use the file descriptor to read the file. The operating system will allow this read even though `chmod` already changed the access rights so that the malicious user is no longer able to open the file. Although the library has a locking mechanism to prevent simultaneous access to the file, malicious processes cannot be assumed to use the locking mechanism.

To prevent this, the library should atomically set the 600 access mode when it creates the file, e.g. via the `mode_t mode` parameter of [`open` on Linux](<https://man7.org/linux/man-pages/man2/open.2.html> "open(2) - Linux manual page"). There is no API for that in .NET 6, but one is being proposed in <https://github.com/dotnet/runtime/issues/67837>. (In the C standard library, [`fopen_s`](<https://en.cppreference.com/w/c/io/fopen> "fopen, fopen_s - cppreference.com") sets a restrictive access mode, unlike the older `fopen` function. However, the resulting `FILE *` would not be trivial to use in .NET, and AFAIK the GNU C Library does not implement `fopen_s`.)

Alternatively, if a `revoke(const char *path)` or `frevoke(int fd)` system call were available, then the library could use one of those to revoke the file descriptors of any malicious processes after `chmod`.

_Originally reported in <https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/pull/168#discussion_r843430829>._

**Comment by pmaytak** [comment]
@KalleOlaviNiemitalo Thanks for the informative feedack.
