### ISSUE TITLE
Obsolete code in documentation

### ISSUE THREAD

**Issue by LukeTOBrien** [AzureAD/microsoft-authentication-extensions-for-dotnet#193]
Hello,

I am just adding OAuth2 caching for my company and I used the code found in [the documentation](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/wiki/Cross-platform-Token-Cache#code) but I am getting the warning:  

> Public Overloads Sub New(cacheFileName As String, cacheDirectory As String, clientId As String)' is obsolete: 'Use StorageCreationPropertiesBuilder(string, string) instead. If you need to consume the CacheChanged event then also use WithCacheChangedEvent(string, string)'.

So I have instead used the code [on MSDN](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=desktop#configuring-the-token-cache-1) with no warning.  
The difference seems to be that the code on MSDN doesn't use the client ID but I don't know why....

Just a little issue but just to let you know.

Luke

**Comment by bgavrilMS** [comment]
Thanks for letting us know @LukeTOBrien . I updated the wiki.
