### ISSUE TITLE
Do I need to use this library?

### ISSUE THREAD

**Issue by NickDarvey** [AzureAD/microsoft-authentication-extensions-for-dotnet#207]
I'm already using [MSAL.NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) in a MAUI app and it seems to support token caching. Am I supposed to be using this library too? (Are tokens stored unencrypted by the built-in token caching and this library adds encrpytion?)

**Comment by pmaytak** [comment]
Sorry for the late reply. By default MSAL caches in-memory - when the PublicClientApp or ConfidentialClientApp instance is disposed of, so is the cache. This library is recommended for desktop apps like desktop MAUI. It does support encryption using OS-specific encryption methods. The default in-memory MSAL cache does not. More info in [Token cache serialization in MSAL.NET
](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-token-cache-serialization?tabs=desktop).
