### ISSUE TITLE
On the encryption problem of AcquireTokenInteractive storage tokens

### ISSUE THREAD

**Issue by duwenlong2** [AzureAD/microsoft-authentication-extensions-for-dotnet#215]
I used IPublicClientApplication. AcquireTokenInteractive to store tokens for Azure's Onenote, compared to my previous use of ProtectedData. Protect (args. TokenCache. SerializeMsalV3(), null, DataProtectionScope. CurrentUser); Do storage,

Our review team is now asking me why storage encryption was not done locally after using AcquireTokenInteractive. However, based on the current documentation, I am unable to retrieve relevant information for explanation, so I have raised a question here. Can you help me answer this? This is quite urgent.

**Comment by bgavrilMS** [comment]
Not sure I undersatnd the question. See the example usage: 

https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/main/sample/ManualTestApp/ExampleUsage.cs#L38

Are you saying that the file on Windows is not encrypted?

**Comment by duwenlong2** [comment]
I am using   var cacheHelper = await MsalCacheHelper.CreateAsync(storageProperties).ConfigureAwait(false);  return cacheHelper;
I need to provide the security review team with an explanation that my locally stored token is encrypted, but I cannot find the relevant explanation in the document

**Comment by duwenlong2** [comment]
@bgavrilMS  hi Do you have any updates？

**Comment by bgavrilMS** [comment]
This is the wiki - it describes the security aspect https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/wiki/Cross-platform-Token-Cache#encryption-and-storage

Unless you explicity opt-out of encryption, the token cache will be stored safely as mentioned above. 

This solution is used by several Microsoft product, including Visual Studio and Azure CLI
