### ISSUE TITLE
GitHub Releases Appear Outdated

### ISSUE THREAD

**Issue by reillysiemens** [AzureAD/microsoft-authentication-extensions-for-dotnet#217]
According to the `README.md` the latest release is `2.32.0` and [nuget.org](https://www.nuget.org/packages/Microsoft.Identity.Client.Extensions.Msal) agrees, but currently the [releases](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/releases) page is missing the following releases
- `2.29.0`
- `2.30.0`
- `2.31.0`
- `2.32.0`

The corresponding Git tags also appear to be missing. Is this just an oversight?

**Comment by pmaytak** [comment]
The latest releases only had an update to the latest Microsoft.Identity.Client version. I've updated the release page. Starting with the next release, this project has been moved into the [main MSAL.NET repo](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), so the release notes should be more accurate.
