### ISSUE TITLE
AadIssuerValidator usage

### ISSUE THREAD

**Issue by rhizohm** [AzureAD/microsoft-authentication-extensions-for-dotnet#30]
The code in this file: https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/master/src/Microsoft.Identity.Client.Extensions.Web/Resource/AadIssuerValidator.cs 

is replicated in many MSFT samples using AADv2, aka https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs

Also, this code is not part of a nuget package, even a preview, at this time.

should one just copy this code into their own project if they want to use the AadIssuerValidator?

**Comment by jmprieur** [comment]
@rhizohm we are working on productizing this code (coming from samples indeed), with the goal of releasing a NuGet package
cc: @MarkZuber @brentschmaltz @henrik-me

**Comment by henrik-me** [comment]
@jmprieur @MarkZuber : Perhaps we should add a roadmap to the wiki?

**Comment by jmprieur** [comment]
@henrik-me : yes we should

**Comment by brentschmaltz** [comment]
@jmprieur @henrik-me I did first pass cleanup of AadIssuerValidator.

**Comment by jmprieur** [comment]
@brentschmaltz 
can I merge all the changes you proposed in the PR? (I would think so)

cc: @jmprieur @MarkZuber @kalyankrishna1 @TiagoBrenck

**Comment by brentschmaltz** [comment]
@jmprieur please pull them in. I expect to be able to continue in about a week. Is there any specific place you would like to prioritize?

**Comment by allenwux** [comment]
Any update on this? It is very confusing if the sample code in documentation doesn't work.

**Comment by jmprieur** [comment]
@allenwux : did you mean that https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/Resource/AadIssuerValidator.cs still does not work?
We have unit tests etc .... are we missing a case? can you please elaborate ?

**Comment by allenwux** [comment]
the code sample in the documentation doesn't work:
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-app-configuration

Can't find the AadIssuerValidator class after adding the nuget package

That documentation page needs some update anyway. I was not able to follow it.

**Comment by udlose** [comment]
Is this in a nuget package yet for AspNetCore v2.2?

**Comment by jmprieur** [comment]
@udlose : not yet. Meanwhile you can use the following project:
https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/blob/master/Microsoft.Identity.Web/README.md

**Comment by jmprieur** [comment]
@allenwux : I plan to update https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-sign-user-app-configuration soon

**Comment by jmprieur** [comment]
I made it clear that the code is no longer here. See PR https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/pull/45

See https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/tree/master/src/Microsoft.Identity.Client.Extensions.Web
