### ISSUE TITLE
Make FallBackAuthority and AzureADIssuerMetadataUrl Configurable

### ISSUE THREAD

**Issue by rhizohm** [AzureAD/microsoft-authentication-extensions-for-dotnet#31]
Right now  FallBackAuthority and AzureADIssuerMetadataUrl are hardcoded. Can you make these configurable with defaults to the most common one?

**Comment by jmprieur** [comment]
@rhizohm 
can you please explain your scenario? Why is it important for you that the URL is configurable? (how is it blocking you)
The reason I'm asking is this class is only for Azure AD, and the metadata document already contains information about all the Microsoft clouds.

feel free to contact me directly if needed.

**Comment by jmprieur** [comment]
BTW, @rhizohm you might be interested in this issue https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/issues/98 (not sure this is related to your request)

**Comment by ideal-it-solutions** [comment]
@jmprieur Hi  please can i get some directives on how to use this nugget? i know this is not part of the previous conversation. Any assistance will truly be appreciated.

**Comment by jmprieur** [comment]
There is no NuGet yet. See https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/tree/master/src/Microsoft.Identity.Client.Extensions.Web
