### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by pjt33** [AzureAD/microsoft-authentication-extensions-for-dotnet#34]
I don't see any documentation, or links to documentation on MSDN, to outline what this library does or what use cases it is intended to help.

**Comment by jmprieur** [comment]
You are right, @pjt33 
We plan to work on documenting and also publishing a NuGet package for one of the 3 libraries.

**Comment by bgavrilMS** [comment]
I've added documentation for the MSAL desktop extension, specifically for the token cache - see the wiki. 

We do not maintain Microsoft.Identity.Web here, we were considering it at some point, but this hasn't happened so far. We may remove it from this repo in the future, as we invest more in it. 

Closing this..
