### ISSUE TITLE
MsalCacheHelper.GetAccountIdentifiersAsync needs CrossPlatLock

### ISSUE THREAD

**Issue by JPWilli** [AzureAD/microsoft-authentication-extensions-for-dotnet#42]
When reacting to a cachefile changed event, we create a new PCA and read the cache, looking for added/removed accounts. This isn't behind a CrossPlatLock though, so it can and will try to access the actual cache when it's not available. The fix is to add a CrossPlatLock in the temporary PCA created in that method.

**Comment by bgavrilMS** [comment]
Closing as this should have been released in 2.2.0-preview based on Mark's comment
