### ISSUE TITLE
When installing the NuGet package, a link to the license file is added to the .csproj

### ISSUE THREAD

**Issue by estiller** [AzureAD/microsoft-authentication-extensions-for-dotnet#44]
For some reason, when installing the NuGet package in a .NET Core console app, a link to the package's License file appears under the .csproj.
![image](https://user-images.githubusercontent.com/584195/64864793-88083100-d640-11e9-88b7-9941117dd9c8.png)

When trying to remove this link, I get the following message:
![image](https://user-images.githubusercontent.com/584195/64864865-aff79480-d640-11e9-8efe-3c66a4984192.png)

Examining this file reveals the following section which adds the link to the License file:
```xml
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <None Include="$(NuGetPackageRoot)microsoft.identity.client.extensions.msal\2.1.0-preview\contentFiles\any\netcoreapp2.1\LICENSE" Condition="Exists('$(NuGetPackageRoot)microsoft.identity.client.extensions.msal\2.1.0-preview\contentFiles\any\netcoreapp2.1\LICENSE')">
      <NuGetPackageId>Microsoft.Identity.Client.Extensions.Msal</NuGetPackageId>
      <NuGetPackageVersion>2.1.0-preview</NuGetPackageVersion>
      <NuGetItemType>None</NuGetItemType>
      <Private>False</Private>
      <Link>LICENSE</Link>
    </None>
  </ItemGroup>
```

Is this intentional? I believe it is a bug and not a feature.
I tried on both VS2017 and VS2019 Preview.

**Comment by jmprieur** [comment]
@bgavrilMS : I don't think that this is the case in the one generated from the MSAL.NET repo?
