### ISSUE TITLE
Deployment to nuget.org is failing

### ISSUE THREAD

**Issue by neilhuiz** [AzureAD/microsoft-authentication-extensions-for-dotnet#46]
All releases in Azure DevOps for this repo have failed. It looks like the access token for nuget.org is invalid or expired. Example: https://identitydivision.visualstudio.com/IDDP/_releaseProgress?_a=release-environment-logs&releaseId=13686&environmentId=14399

**Comment by jmprieur** [comment]
@bgavrilMS : would you know if this is still the case?

**Comment by bgavrilMS** [comment]
It was using an older connection to NuGet. I've updated it now.
