### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-extensions-for-dotnet#47]
@henrik-me @jmprieur - 
Can we archive this repo now that the extensions are in the same repo as MSAL ? There is one outstanding PR from Mark and 1-2 issues that we'd need to move.

**Comment by jmprieur** [comment]
@bgavrilMS : what do we want to do with Mark's PR?

**Comment by jmprieur** [comment]
@bgavrilMS as discussed, we won't probably archive this repo.
Proposing to close this issue (we'll reopen if we change our mind)
