### ISSUE TITLE
MacKeyChain uses "Legacy" APIs

### ISSUE THREAD

**Issue by ghelyar** [AzureAD/microsoft-authentication-extensions-for-dotnet#67]
The APIs that are being used on MacOS are not deprecated, but are marked as "Legacy" and their use is discouraged.

https://developer.apple.com/documentation/security/keychain_services/keychain_items?language=objc#1659107

This may not be an immediate issue, but Apple may deprecate and then remove them in the future, and they don't support more advanced scenarios such as [Sharing Access to Keychain Items Among a Collection of Apps](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps?language=objc).

The P/Invoke also doesn't use utf-8 encoded strings, so may cause issues with non-ascii characters in the service or account names.

**Comment by henrik-me** [comment]
@ghelyar : Thanks a lot for reporting. Added to the backlog. We will happily take a PR helping address this.

**Comment by bgavrilMS** [comment]
Note that Git Credential Manager have written the interop code that allows for this: 

https://github.com/microsoft/Git-Credential-Manager-Core/tree/master/src/shared/Microsoft.Git.CredentialManager/Interop/MacOS
