### ISSUE TITLE
WCF Azure App service 

### ISSUE THREAD

**Issue by mike7ang1rdz** [AzureAD/microsoft-authentication-extensions-for-dotnet#70]
Hello, I have a WinForms (legacy) client application that consumes WCF services and uses its own authentication model...   (on-premises)

However, the company wants to migrate to Azure and use an app service to host the wcf and authenticate it with Azure AD  (JWT).   

Do you have any example with this scenario?

**winforms +  (app service + wcf + azure AD (JWT))**

Thank you

**Comment by bgavrilMS** [comment]
Hi @mike7ang1rdz - sorry for the long delay. Please post these questions on the MSAL library issue tracker https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
