### ISSUE TITLE
[FEATURE ASK] Provide general encryption and decryption method

### ISSUE THREAD

**Issue by erich-wang** [AzureAD/microsoft-authentication-extensions-for-dotnet#92]
MSAL extension should provide encrption/decryption methods for general purpose, it may look like:

```csharp
	byte[] Encrypt(SecureString ); //or return as base64 string?
	SecureString Decrypt(byte[] );
```

Besides token info, we want to protect client secret of service principal as well, currently in Azure PowerShell client secret of service principal is saved as plain text which doesn’t meet secret review. MSAL extension for Python has provided similar functionality, you may find the sample code [here](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/dev/sample/persistence_sample.py)

**Comment by henrik-me** [comment]
@bgavrilMS : this ask is dependent on the API review that Ray has out.

**Comment by jmprieur** [comment]
@henrik-me. There is a partner ask for this one: [Epic 1396293: Provide general encryption and decryption method](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1396293)
Is it something we want to take in Q1?

cc: @bgavrilMS @maliksahil

**Comment by bgavrilMS** [comment]
I propose we close it.

**Comment by jmprieur** [comment]
you mean we reject the partner request @bgavrilMS ?

**Comment by dingmeng-xue** [comment]
Is it not a valid requirement?

**Comment by jmprieur** [comment]
We'll provide it part with the token cache serializers in MIcrosoft.Identity.Web;
See https://github.com/AzureAD/microsoft-identity-web/issues/1044

**Comment by bgavrilMS** [comment]
This is not for confidential client apps @jmprieur, this is for public client apps.

I think we should expose the storage primitives, similar to how Msal.py do it?

**Comment by jmprieur** [comment]
yes, this sounds good, @bgavrilMS

**Comment by pmaytak** [comment]
Included in [MSAL.NET Extensions 2.19.0 release](https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/releases/tag/2.19.0).
