### ISSUE TITLE
link to linux fallback configuration example does not work

### ISSUE THREAD

**Issue by bchuecos** [AzureAD/microsoft-authentication-extensions-for-dotnet#95]
I'm trying to test whether token caching works for our desktop app on linux, but I can't do it over ssh. I noticed the wiki states 

> KeyRings does not work in headless mode (e.g. when connected over SSH or when running Linux in a container) due to a dependency on X11. To overcome this, a fallback to a plaintext file can be configured. See this example for how to configure it.

But when I click the link to the example, I get a github 404 error. Can the wiki please be updated?

**Comment by isra-fel** [comment]
Hi @bchuecos I think they moved the example here: https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/master/sample/ManualTestApp/ExampleUsage.cs

@jmprieur could you fix the link in wiki https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/wiki/Cross-platform-Token-Cache#linux-fallback

Thanks

**Comment by jmprieur** [comment]
Thanks for the heads-up @isra-fel 
I just fixed it.
