### ISSUE TITLE
"SecKeychainFindGenericPassword failed with error code -25293" when calling RegisterCache()

### ISSUE THREAD

**Issue by bchuecos** [AzureAD/microsoft-authentication-extensions-for-dotnet#96]
We're trying to enable user token caching in our desktop application in OS X. We modeled the caching after the manual test app https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/d32a5a6eb699cc652ca08c477140af1a0a0dbd42/tests/ManualTestApp/Program.cs. However, when running on mac, once we sign in the first time, get a Keychain Access entry and then try to sign in again, we get the error "**SecKeychainFindGenericPassword failed with error code -25293**" with the following stack trace: 
  `at Microsoft.Identity.Client.Extensions.Msal.MacKeyChain.DeleteKey(String serviceName, String accountName)
at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.ClearCore()
at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.RegisterCache(ITokenCache tokenCache)`.

The problem goes away after we manually go into Keychain Access, click on the keychain entry corresponding to our token, and change the Access Control setting to "Allow all applications to access this item". I noticed the wiki mentions this: 

> Mac offers a more restricted scope, ensuring that only the application that created the cache can access it, and prompting the user if others apps want access.

Does this mean this is the intended behavior? Is there anyway to circumvent this issue that doesn't require users to manually change the Keychain Access Control settings for their entry?

**Comment by henrik-me** [comment]
@bgavrilMS ?

**Comment by bgavrilMS** [comment]
@bchuecos - apologies for the late reply. Is this happening all the time? What version of MacOs are you using?

**Comment by jmprieur** [comment]
@bchuecos : proposing to close this one, as you have not replied.
Feel free to reopen if you still have the issue.
