### ISSUE TITLE
[Bug] token cache file not getting created when referencing DLLs instead of nupkg

### ISSUE THREAD

**Issue by hiteshdasikamw** [AzureAD/microsoft-authentication-extensions-for-dotnet#97]
```
            app = PublicClientApplicationBuilder.Create(clientId).WithTenantId(tenant).WithAuthority(authority).Build();
            StorageCreationPropertiesBuilder storageCreationPropertiesBuilder = new StorageCreationPropertiesBuilder("tokenCache.dat", "tokencache", clientId).
                WithLinuxKeyring("test", "default", "Get Access Token",
                new System.Collections.Generic.KeyValuePair<string, string>("Version", "1"),
                new System.Collections.Generic.KeyValuePair<string, string>("ProductGroup", "Test")).WithMacKeyChain("Test", "default");
            var task = Task.Run(async () => await MsalCacheHelper.CreateAsync(storageCreationPropertiesBuilder.Build()));
            MsalCacheHelper msalCacheHelper = task.Result;
            try
            {
                msalCacheHelper.RegisterCache(app.UserTokenCache);
                Task<AuthenticationResult> result = app.AcquireTokenByIntegratedWindowsAuth(scopes).WithUsername(username).ExecuteAsync();
                Console.Write(result.Result.AccessToken);
            }

```

I am using **Microsoft.Identity.Client -> 4.15.0 and Microsoft.Identity.Client.Extensions -> 2.12.0**. The issue is that **tokencache** folder gets created but **tokenCache.dat** doesnt get created. I am having the DLLs downloaded from the respective Nuget packages and adding them as a Reference in the .NET core console project.

This works absolutelyt fine and cache file gets created If I directly link the package from Nuget package manager. I am not really sure what is happening here. It might not be a bug, but want to see if anyone can help here?

**Comment by bgavrilMS** [comment]
Hi @hiteshdasikamw - so it looks like things are working well if you are using NuGet packages, but not so good if you are using DLLs. Obvious solution is to not use DLLs :) as can be difficult to reproduce what NuGet is trying to do.

MSAL has a pretty complex build output, as it creates both lib and ref assemblies. You should reference the lib assembly, as the ref assemblies have no code.

**Comment by bgavrilMS** [comment]
Latest MSAL library no longer uses reference assemblies. It should be pretty simple to use DLLs if you understand multi-targetting.
