### ISSUE TITLE
MsalCacheHelper.CreateAsync throws MsalClientException when using an ADFS ClientId

### ISSUE THREAD

**Issue by schaabs** [AzureAD/microsoft-authentication-extensions-for-dotnet#98]
When trying to use `MsalCacheHelper` with a ClientId for ADFS which is not a GUID the followoing exception is thrown.

```
MSAL.NetCore.4.16.1.0.MsalClientException:
ErrorCode: client_id_must_be_guid
Microsoft.Identity.Client.MsalClientException: Error: ClientId is not a Guid.
  at Microsoft.Identity.Client.AbstractApplicationBuilder1.Validate() 
  at Microsoft.Identity.Client.PublicClientApplicationBuilder.Validate() 
  at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.GetAccountIdentifiersAsync(StorageCreationProperties storageCreationProperties, TraceSourceLogger logger) 
  at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateAsync(StorageCreationProperties storageCreationProperties, TraceSource logger)
```

To reproduce this you can run the following.

``` c#
StorageCreationProperties storageProperties = new StorageCreationPropertiesBuilder("msal.cache", ".", "AdfsNonGuidClientId").Build();

await MsalCacheHelper.CreateAsync(storageProperties).ConfigureAwait(false);
```

To work around this issue I'm updating the code to supply a random guid rather than a specific client id. The client id doesn't seem to be necessary as the `MsalCacheHelper` only uses it to create a `PublicClientApplication` to iterate through the accounts in a serialized cache, in the method `GetAccountIdentifiersAsync`

https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/1a2de3a3ae272f288dbeda8fc242e7846892848f/src/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs#L91-L127

**Comment by bgavrilMS** [comment]
The workaround mentioned here will ensure token caching works, however the event `CacheChanged` will not work.

**Comment by jmprieur** [comment]
@bgavrilMS this is really an MSAL.NET issue? if the ADFS client ID needs to be a GUID, do we want to relax the constraint in MSAL.NET when we detect an ADFS authority?

**Comment by bgavrilMS** [comment]
@jmprieur - it's not an MSAL.NET issue, it is a cache extension issue.

**Comment by bgavrilMS** [comment]
As discussed offline - the cache needs to be able to read the accounts and only MSAL can do that. So the cache creates a PublicCLientApplication object with the given client ID, but this doesn't work for ADFS / other cloud authorities. 

Solution would be for users to provide authority as well.

**Comment by jmprieur** [comment]
Todo:
1. Add a new property `Authority` to `StorageCreationPropertiesBuilder`, which default value is the Azure public cloud authority
2. Have `MsalCacheHelper.GetAccountIdentifiersNoLockAsync` use the authority when creating the public client application
